### ISSUE TITLE
systemd doesn't allow two active units to specify the same BusName (i.e. timedated and timedatex)

### ISSUE THREAD

**Issue by AdamWill** [mlichvar/timedatex#2]
Well, @poettering has proclaimed:

https://github.com/systemd/systemd/issues/609

"Yeah, bus names must be unique. systemd tracks the service status of bus services by their bus names (BusName= binds the status of the unit to the status of the name on the bus, hence the unit name and the bus name must be unique and their mappings bijective).

The stuff "timedatex" is doing is simply not supported, and never was."

So, timedatex effectively conflicts with systemd-timedated. Obviously this is kind of what it's intended to do, and this is sort of a problem.

I suppose timedatex could ship a `systemd-timedated.service` which just disables it? Not really sure what the best approach is here.

Note the problem this eventually causes is quite serious, and is where I came into this mess: https://bugzilla.redhat.com/show_bug.cgi?id=1244023 - on Fedora 23, gnome-initial-setup crashes when it runs into this problem, leaving a freshly-installed system sitting at a blue screen with no obvious way forward.

**Comment by poettering** [comment]
I think the right approach is to stop making GNOME a frontend for configuring full-blown NTP servers... But anyway, Fedora has to take the burden for this...
