### ISSUE TITLE
100% CPU utilization

### ISSUE THREAD

**Issue by tvollstaedt** [mlichvar/timedatex#3]
Hi, I'm running Fedora 26 alpha on a Lenovo X1 Yoga and experience 100% CPU utilization from timedatex (0.4) since the last system update a few days ago:

```
PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                              
1945 root      20   0  261188   4668   4240 R  99,7  0,0  20:37.48 timedatex   
```
Restarting the service does not help.

Journal also shows no real useful info:
```
-- Reboot --
Mai 08 14:14:53 ofigo-pc17 systemd[1]: Starting System clock and RTC settings service...
Mai 08 14:14:54 ofigo-pc17 systemd[1]: Started System clock and RTC settings service.
Mai 08 16:37:56 ofigo-pc17 systemd[1]: Starting System clock and RTC settings service...
Mai 08 16:37:56 ofigo-pc17 systemd[1]: Started System clock and RTC settings service.
```

Any advise on how to debug this issue?

**Comment by M5oul** [comment]
Same here.
After Fedora 26 Alpha upgrade with [`timedatex` package update](https://apps.fedoraproject.org/packages/timedatex), `timedatex` process take 100% CPU of a core.
I could kill it.

https://bugzilla.redhat.com/show_bug.cgi?id=1450628

**Comment by mlichvar** [comment]
Thanks for the report. It seems it is actually a bug in glib2 which affects also LibreOffice.

https://bugzilla.gnome.org/show_bug.cgi?id=761102
